### ISSUE TITLE
CORS issue when running in Ionic/Cordova on iOS

### ISSUE THREAD

**Issue by andufratu** [Mangopay/cardregistration-js-kit#55] opened 2020-08-19 13:03 UTC
Hi,

we are running into issues with the CORS preflight request when using the library in a Ionic/Cordova project on iOS. 
![image](https://user-images.githubusercontent.com/1881236/90638035-114ebd00-e22d-11ea-8057-cb8de5540d25.png)
As can be seen in the screenshot, Ionic uses a custom schema on iOS which does not pass the CORS preflight request on the MangoPay servers. Is there any way to bypass this error?

Thank you.

**Comment by raphaelstz** [comment] 2020-08-20 21:00
Im having a CORS issue as well when using registerCard method on ionic 4 on chrome preview.

**Comment by mangomaxoasis** [comment] 2020-08-25 08:54
Hi @raphaelstz and @andufratu 
This issue is ongoing, we'll keep you updated,
Max

**Comment by mangomaxoasis** [comment] 2020-09-04 14:19
Hi @andufratu , @raphaelstz 
Enacting changes to how our API, as well as that of banking partners, processes the origin header is not something we can easily enact.
This resources talks about a few solutions 
https://fdezromero.com/cors-errors-in-ionic-apps/ 
We have prioritized this issue on our roadmap, but cannot give a delivery date at this stage.
Best,
Max

**Comment by andufratu** [comment] 2020-09-07 08:12
@mangomaxoasis, unfortunately those solutions can't be applied in this case, since the failing requests are made from the MangoPay library and we have no way to intercept them.

**Comment by mangomaxoasis** [comment] 2020-09-07 13:00
Hi ,

We are currently looking into a plugin for Cordova, but it's an ongoing subject. 

Here is another solution, a bit more manual but still nice. 

As the issue seems to be specific to IOS, for the card registration function (which is where the problem is, as it calls a banking partner from the front end) 
Can you try replacing JS code with code from the IOS card reg kit in objC. 

https://github.com/Mangopay/cardregistration-ios-kit/blob/master/mangopay/MPAPIClient.h

Cordova offers the option of adding in native code where appropriate. 

As such the request will come from the device, not necessarily the browser.

**Comment by mangomaxoasis** [comment] 2020-09-10 16:28
HI Guys, 
The inclusion of native code is what we deem the best solution in the medium term.
I'm closing this issue.
max

**Closed by mangomaxoasis** 2020-09-10 16:28 UTC
